os: linux
dist: xenial

language: c

cache: ccache

compiler:
  - gcc

env:
  global:
      - MAKEFLAGS="-j 2"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq gcc cmake git ccache build-essential

before_script:
  - mkdir /home/travis/build/bin/tftpstats
  - cd    /home/travis/build/bin/tftpstats
  - cmake /home/travis/build/louiscyphre/tftpstats -DCMAKE_INSTALL_PREFIX=/home/travis/build -DCMAKE_SOURCE_DIR=/home/travis/build/louiscyphre/tftpstats -DCMAKE_BINARY_DIR=/home/travis/build/bin/tftpstats -DROOT_INCLUDE_DIR=/home/travis/build/bin/tftpstats -DDEPENDENCY_PROJECT=ON
script:
  - make
